"""Add external_notification_id to alert_notifications

Revision ID: 0394036f545e
Revises: j4k5l6m7n8o9
Create Date: 2026-02-24 18:28:11.580028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0394036f545e'
down_revision: Union[str, None] = 'j4k5l6m7n8o9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interview_questions_company_id', table_name='interview_questions')
    op.drop_index('ix_interview_questions_role', table_name='interview_questions')
    op.drop_table('interview_questions')
    op.add_column('alert_notifications', sa.Column('external_notification_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_alert_notifications_external_notification_id'), 'alert_notifications', ['external_notification_id'], unique=False)
    op.drop_constraint('uq_job_embeddings_job_id', 'job_embeddings', type_='unique')
    op.drop_index('ix_job_embeddings_job_id', table_name='job_embeddings')
    op.create_index(op.f('ix_job_embeddings_job_id'), 'job_embeddings', ['job_id'], unique=True)
    op.drop_constraint('uq_user_job_interactions_user_job', 'user_job_interactions', type_='unique')
    op.drop_index('ix_users_oauth_provider_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_oauth_provider_id', 'users', ['oauth_provider', 'oauth_provider_id'], unique=False)
    op.create_unique_constraint('uq_user_job_interactions_user_job', 'user_job_interactions', ['user_id', 'job_id'])
    op.drop_index(op.f('ix_job_embeddings_job_id'), table_name='job_embeddings')
    op.create_index('ix_job_embeddings_job_id', 'job_embeddings', ['job_id'], unique=False)
    op.create_unique_constraint('uq_job_embeddings_job_id', 'job_embeddings', ['job_id'])
    op.drop_index(op.f('ix_alert_notifications_external_notification_id'), table_name='alert_notifications')
    op.drop_column('alert_notifications', 'external_notification_id')
    op.create_table('interview_questions',
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('interview_stage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('upvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='interview_questions_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='interview_questions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='interview_questions_pkey')
    )
    op.create_index('ix_interview_questions_role', 'interview_questions', ['role'], unique=False)
    op.create_index('ix_interview_questions_company_id', 'interview_questions', ['company_id'], unique=False)
    # ### end Alembic commands ###
