"""Refactor AlertNotification to store multiple jobs

Revision ID: 0a6c7dddccf5
Revises: 723144573053
Create Date: 2025-12-08 12:52:38.512409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a6c7dddccf5'
down_revision: Union[str, None] = '723144573053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_notifications', sa.Column('job_position_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('alert_notifications', sa.Column('job_count', sa.Integer(), nullable=False))
    op.add_column('alert_notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('alert_notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('alert_notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_alert_notifications_job_position_id', table_name='alert_notifications')
    op.drop_constraint('alert_notifications_job_position_id_fkey', 'alert_notifications', type_='foreignkey')
    op.drop_column('alert_notifications', 'job_position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_notifications', sa.Column('job_position_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('alert_notifications_job_position_id_fkey', 'alert_notifications', 'job_positions', ['job_position_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_alert_notifications_job_position_id', 'alert_notifications', ['job_position_id'], unique=False)
    op.alter_column('alert_notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('alert_notifications', 'updated_at')
    op.drop_column('alert_notifications', 'created_at')
    op.drop_column('alert_notifications', 'job_count')
    op.drop_column('alert_notifications', 'job_position_ids')
    # ### end Alembic commands ###
