"""Initial schema with all models

Revision ID: 108a0937474b
Revises: 
Create Date: 2025-12-01 13:24:27.526008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '108a0937474b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('careers_url', sa.String(length=500), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('scraping_config', sa.JSON(), nullable=False),
    sa.Column('scraping_frequency', sa.String(length=100), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('locations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('departments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('employment_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('remote_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('seniority_levels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notification_method', sa.String(length=50), nullable=False),
    sa.Column('notification_config', sa.JSON(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('job_positions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('remote_type', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('salary_range', sa.JSON(), nullable=True),
    sa.Column('requirements', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('benefits', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_positions_company_active', 'job_positions', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_job_positions_company_id'), 'job_positions', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_positions_department'), 'job_positions', ['department'], unique=False)
    op.create_index('ix_job_positions_department_active', 'job_positions', ['department', 'is_active'], unique=False)
    op.create_index(op.f('ix_job_positions_first_seen_at'), 'job_positions', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_job_positions_is_active'), 'job_positions', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_positions_location'), 'job_positions', ['location'], unique=False)
    op.create_index('ix_job_positions_location_active', 'job_positions', ['location', 'is_active'], unique=False)
    op.create_index(op.f('ix_job_positions_scraped_at'), 'job_positions', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_job_positions_status'), 'job_positions', ['status'], unique=False)
    op.create_index(op.f('ix_job_positions_title'), 'job_positions', ['title'], unique=False)
    op.create_table('scraping_sessions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('jobs_removed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('scraper_config_snapshot', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_sessions_company_id'), 'scraping_sessions', ['company_id'], unique=False)
    op.create_index('ix_scraping_sessions_company_status', 'scraping_sessions', ['company_id', 'status'], unique=False)
    op.create_index('ix_scraping_sessions_started_at', 'scraping_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_scraping_sessions_status'), 'scraping_sessions', ['status'], unique=False)
    op.create_table('alert_notifications',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notifications_alert_id'), 'alert_notifications', ['alert_id'], unique=False)
    op.create_index('ix_alert_notifications_alert_sent', 'alert_notifications', ['alert_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_alert_notifications_delivery_status'), 'alert_notifications', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_alert_notifications_job_position_id'), 'alert_notifications', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_alert_notifications_sent_at'), 'alert_notifications', ['sent_at'], unique=False)
    op.create_index('ix_alert_notifications_status_sent', 'alert_notifications', ['delivery_status', 'sent_at'], unique=False)
    op.create_index(op.f('ix_alert_notifications_user_id'), 'alert_notifications', ['user_id'], unique=False)
    op.create_index('ix_alert_notifications_user_sent', 'alert_notifications', ['user_id', 'sent_at'], unique=False)
    op.create_table('user_job_applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_position_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_position_id', name='uq_user_job')
    )
    op.create_index(op.f('ix_user_job_applications_job_position_id'), 'user_job_applications', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_user_job_applications_status'), 'user_job_applications', ['status'], unique=False)
    op.create_index(op.f('ix_user_job_applications_user_id'), 'user_job_applications', ['user_id'], unique=False)
    op.create_index('ix_user_job_applications_user_status', 'user_job_applications', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_job_applications_user_status', table_name='user_job_applications')
    op.drop_index(op.f('ix_user_job_applications_user_id'), table_name='user_job_applications')
    op.drop_index(op.f('ix_user_job_applications_status'), table_name='user_job_applications')
    op.drop_index(op.f('ix_user_job_applications_job_position_id'), table_name='user_job_applications')
    op.drop_table('user_job_applications')
    op.drop_index('ix_alert_notifications_user_sent', table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_user_id'), table_name='alert_notifications')
    op.drop_index('ix_alert_notifications_status_sent', table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_sent_at'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_job_position_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_delivery_status'), table_name='alert_notifications')
    op.drop_index('ix_alert_notifications_alert_sent', table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_alert_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    op.drop_index(op.f('ix_scraping_sessions_status'), table_name='scraping_sessions')
    op.drop_index('ix_scraping_sessions_started_at', table_name='scraping_sessions')
    op.drop_index('ix_scraping_sessions_company_status', table_name='scraping_sessions')
    op.drop_index(op.f('ix_scraping_sessions_company_id'), table_name='scraping_sessions')
    op.drop_table('scraping_sessions')
    op.drop_index(op.f('ix_job_positions_title'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_status'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_scraped_at'), table_name='job_positions')
    op.drop_index('ix_job_positions_location_active', table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_location'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_is_active'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_first_seen_at'), table_name='job_positions')
    op.drop_index('ix_job_positions_department_active', table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_department'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_company_id'), table_name='job_positions')
    op.drop_index('ix_job_positions_company_active', table_name='job_positions')
    op.drop_table('job_positions')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_active'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
