"""add_external_id_to_job_positions

Revision ID: 73ba5a2eaba3
Revises: 108a0937474b
Create Date: 2025-12-01 15:26:48.524272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ba5a2eaba3'
down_revision: Union[str, None] = '108a0937474b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_positions', sa.Column('external_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_job_positions_external_id'), 'job_positions', ['external_id'], unique=False)
    op.create_index('ix_job_positions_external_id_company', 'job_positions', ['external_id', 'company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_positions_external_id_company', table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_external_id'), table_name='job_positions')
    op.drop_column('job_positions', 'external_id')
    # ### end Alembic commands ###
