"""Add onboarding reminder tracking to users

Revision ID: 7d602df3b491
Revises: 0394036f545e
Create Date: 2026-02-24 22:39:25.280778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d602df3b491'
down_revision: Union[str, None] = '0394036f545e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with server_default=0 so existing rows get 0, then we can remove the default
    op.add_column('users', sa.Column('onboarding_reminder_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_onboarding_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_onboarding_reminder_at')
    op.drop_column('users', 'onboarding_reminder_count')
    # ### end Alembic commands ###
