"""add_source_type_and_duplicate_metadata_to_jobs

Revision ID: b754888d80d2
Revises: 73ba5a2eaba3
Create Date: 2025-12-03 17:50:24.411975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b754888d80d2'
down_revision: Union[str, None] = '73ba5a2eaba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('job_positions', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('job_positions', sa.Column('duplicate_metadata', sa.JSON(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE job_positions SET source_type = 'company_direct' WHERE source_type IS NULL")
    
    # Now make source_type non-nullable
    op.alter_column('job_positions', 'source_type', nullable=False)
    
    # Create index
    op.create_index(op.f('ix_job_positions_source_type'), 'job_positions', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_positions_source_type'), table_name='job_positions')
    op.drop_column('job_positions', 'duplicate_metadata')
    op.drop_column('job_positions', 'source_type')
    # ### end Alembic commands ###
